Custom destinations for modules
coretech/terrafile pull request #13
Opened 2023-02-13 15:07 UTC by ivan-kostko

This feature enables module management with specific destinations, while back compatibility is intact.

Centrally managed: `Terrafile` is located in "root" directory of your terraform code, managing modules in all subfolders / stacks
An example of using `Terrafile` in a root directory:

Let's assume following directory structure structure

```
.
├── iam
│   ├── main.tf
│   └── .....tf
├── networking
│   ├── main.tf
│   └── .....tf
├── onboarding
.
.
.
├── some-other-stack
└── Terrafile
```

In above scenarion Terrafile is not in every single folder but in the "root" of terraform code.

An example usage of centrally managed modules:

```
tf-aws-vpc:
    source:  "git@github.com:terraform-aws-modules/terraform-aws-vpc"
    version: "v1.46.0"
    destination:
        - networking
tf-aws-iam:
    source:  "git@github.com:terraform-aws-modules/terraform-aws-iam"
    version: "v5.11.1"
    destination:
        - iam
tf-aws-s3-bucket:
    source:  "git@github.com:terraform-aws-modules/terraform-aws-s3-bucket"
    version: "v3.6.1"
    destination:
        - networking
        - onboarding
        - some-other-stack
```

The `destination` of module is an array of directories (stacks) where the module should be used.
The module itself is fetched once and copied over to designated destionations.
Final destination of the module is handled in a similar way as in first approach: `$destination/$module_path/$module_key`.

The output of the run is exactly the same in both options.

2023-02-13 17:11 UTC, nritholtz requested changes
Added some typo fixes and minor suggestions on reworking the implementation.

2023-02-13 17:11 UTC, nritholtz commented on README.md
> +An example of default approach (#1) to `Terrafile`:
```suggestion
### Default Approach
An example of default approach (#1) to `Terrafile`
```

2023-02-13 17:11 UTC, nritholtz commented on README.md
> +An example of using `Terrafile` in a root directory:
```suggestion
### Centrally Managed Approach
An example of using `Terrafile` in a root directory (#2):
```

2023-02-14 16:09 UTC, ivan-kostko commented on .gitignore
> +.DS_Store
Done

2023-02-14 16:12 UTC, ivan-kostko commented on main.go
> +	Destination []string `yaml:"destination"`
Accepted and adapted

2023-02-14 16:13 UTC, ivan-kostko commented on main.go
> +					cmd := exec.Command("cp", "-Rf", moduleSrc, dst)
Patrially Accepted and adapted. Hardlinks won't work for folders. However, SymLink does the job ;-). Please, have a look on latest changes

2023-02-14 17:58 UTC, nritholtz requested changes
awesome work! two very minor fixes, otherwise looks good to me

2023-02-14 17:58 UTC, nritholtz commented on main.go
> +			// list of paths to link module to. empty, uless Destinations are more than 1 location
```suggestion
			// list of paths to link module to. empty, unless Destinations are more than 1 location
```

2023-02-14 17:58 UTC, nritholtz commented on main_test.go
> +			os.RemoveAll(testModuleLocation)
```suggestion
			_ = os.RemoveAll(testModuleLocation)
```

2023-02-15 09:26 UTC, ivan-kostko commented
Hi @nritholtz ,

Sorry for off topic, but as we discussed inside our team, the tool is missing `-clean` flag. The issue appears whenever some module is removed from file, but tool does not remove it from filesystem. Hence, we will prepare a separate PR introducing this functionality as soon as this PR is merged.

2023-02-15 12:26 UTC, nritholtz approved these changes

2023-02-15 12:28 UTC, merged